# Copyright (C) 2020 - present Juergen Zimmermann, Hochschule Karlsruhe
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Default values for mongodb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: acme

replicaCount: 1

port: 27017

image:
  name: mongo
  tag: 4.4.1

storage: 1Gi
hostpath: /run/desktop/mnt/host/c/Zimmermann/volumes/mongodb-standalone-4.4/db
admin:
  name: admin
  password:
    key: password
    value: cA==
