# Copyright (C) 2016 - present Juergen Zimmermann, Hochschule Karlsruhe
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# https://github.com/sdeleuze/spring-kotlin-functional/blob/boot/src/main/resources/application.properties
context.initializer.classes: com.acme.kunde.BeansInitializer

server:
  #port: 8080
  compression:
    enabled: true
    mime-types: application/hal+json
    min-response-size: 2KB
  error.whitelabel.enabled: false
  http2.enabled: true
  ssl:
    enabled: true
    enabled-protocols: TLSv1.3,TLSv1.2
    key-alias: microservice
    key-password: zimmermann
    key-store: classpath:keystore.p12
    key-store-password: zimmermann
    key-store-type: PKCS12
    protocol: TLS
    trust-store: classpath:truststore.p12
    trust-store-password: zimmermann
    trust-store-type: PKCS12
  shutdown: graceful

spring:
  application.name: kunde
  aop.proxy-target-class: false
  data.mongodb:
#    authentication-database: admin
    auto-index-creation: false
    #port: 27017
    repositories.type: none
#    database: acme
#    host: localhost
    #password: p
#    username: admin
    uuid-representation: standard
    # https://docs.mongodb.com/manual/reference/connection-string
    # mongodb://[username:password@]host1[:port1][,...hostN[:portN]][/[database][?options]]
    # For MongoDB Replica Set Deployment
#      uri: mongodb://admin:p@localhost/acme?replicaSet=replicaSet&authSource=admin&authMechanism=SCRAM-SHA-256
    # For local testing purposes
    uri: mongodb://admin:p@localhost:27017/acme?authSource=admin&authMechanism=SCRAM-SHA-256
  jackson.default-property-inclusion: non_null
  lifecycle.timeout-per-shutdown-phase: 3s
  mail:
    host: localhost
    port: 5025
    #protocol: smtp
    properties.mail:
      debug: false
      smtp:
        auth: false
        starttls.enable: false
    # Mailserver des IZ
    #host: smtp.hs-karlsruhe.de
    #port: 23
    #username: nnvv0011
    #password: blabla
    # GMail
    #host: smtp.gmail.com
    #port: 587
    #properties.mail.smtp.starttls.enable: true
  main.lazy-initialization: true
  output.ansi.enabled: ALWAYS
  security.user.password: p
  spel.ignore: true
  thymeleaf.enabled: true
  xml.ignore: true
  security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: http://localhost:9900/auth/realms/swa
            jwk-set-uri: http://localhost:9900/auth/realms/swa/protocol/openid-connect/certs

info.app:
  author: Juergen Zimmermann
  lecture: Softwarearchitektur
  semester: 3
  studiengang: Wirtschaftsinformatik (Bachelor)

# https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-logging-file-output
logging:
  file.name: build/log/application.log
  # z.B. TRACE beinhaltet auch DEBUG, INFO, WARN, ERROR, FATAL
  level:
    org:
      hibernate.validator.internal.xml:
        ValidationXmlParser: WARN
        ValidationBootstrapParameters: WARN
      mongodb.driver.cluster: WARN
      springframework:
        boot.devtools.autoconfigure.ConditionEvaluationDeltaLoggingListener: WARN
        security.core:
          userdetails.User: ERROR
          #SpringSecurityCoreVersion: ERROR

management:
  endpoints.web.exposure.include: "*"
  endpoint:
    health.enabled: true
    shutdown.enabled: true

# --------------------------------------------------------
# E i g e n e   P r o p e r t i e s
# --------------------------------------------------------
mail:
  from: Theo Test <theo@test.de>
  sales: Maxi Musterfrau <maxi.musterfrau@test.de>
  topic: mail

---
spring:
  config.activate.on-profile: dev
  devtools:
    livereload.enabled: false
    restart.trigger-file: /restart.txt
  #http.log-request-details: true
  # siehe org.springframework.boot.autoconfigure.jackson.JacksonProperties
  jackson.serialization.indent-output: true
  # -Dreactor.trace.operatorStacktrace=true
  reactor.debugagent.enabled: true
  thymeleaf.cache: false

logging.level:
  com.acme: TRACE
  io.mockk.impl.recording.states.AnsweringState: DEBUG
  org:
    junit.jupiter.engine.descriptor.TestInstanceLifecycleUtils: WARN
    springframework:
      http.codec.json.Jackson2JsonEncoder: DEBUG
      web.server.adapter.HttpWebHandlerAdapter: DEBUG
      boot.test.context.SpringBootTestContextBootstrapper: WARN
      test.context.support:
        AbstractContextLoader: WARN
        AnnotationConfigContextLoaderUtils: WARN
        DefaultTestContextBootstrapper: WARN
  #reactor.netty.http.client: DEBUG

management:
  endpoint:
    env.enabled: true
    health.show-details: ALWAYS
    mappings.enabled: true
  endpoints.web.cors:
    allowed-origins: http://localhost,http://127.0.0.1,https://localhost,https://127.0.0.1
    allowed-methods: GET,POST,PUT,PATCH,DELETE,OPTIONS
    allowed-headers: Origin,Content-Type,Accept,Authorization,Access-Control-Allow-Origin,Access-Control-Allow-Methods,Access-Control-Allow-Headers,Access-Control-Expose-Headers,Allow,Content-Length,Date,If-None-Match,If-Match,Last-Modified,If-Modified-Since
    exposed-headers: Location,ETag,Access-Control-Allow-Origin,Access-Control-Allow-Headers

kunde:
  password: p
  password-falsch: FALSCH
